// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RandGenerator is an autogenerated mock type for the randGenerator type
type RandGenerator struct {
	mock.Mock
}

type RandGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *RandGenerator) EXPECT() *RandGenerator_Expecter {
	return &RandGenerator_Expecter{mock: &_m.Mock}
}

// Uint32 provides a mock function with no fields
func (_m *RandGenerator) Uint32() uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Uint32")
	}

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

// RandGenerator_Uint32_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Uint32'
type RandGenerator_Uint32_Call struct {
	*mock.Call
}

// Uint32 is a helper method to define mock.On call
func (_e *RandGenerator_Expecter) Uint32() *RandGenerator_Uint32_Call {
	return &RandGenerator_Uint32_Call{Call: _e.mock.On("Uint32")}
}

func (_c *RandGenerator_Uint32_Call) Run(run func()) *RandGenerator_Uint32_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RandGenerator_Uint32_Call) Return(_a0 uint32) *RandGenerator_Uint32_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RandGenerator_Uint32_Call) RunAndReturn(run func() uint32) *RandGenerator_Uint32_Call {
	_c.Call.Return(run)
	return _c
}

// NewRandGenerator creates a new instance of RandGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRandGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *RandGenerator {
	mock := &RandGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
